/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CrateRoom: typeof import('./src/components/CrateRoom.vue')['default']
    Doll: typeof import('./src/components/Doll.vue')['default']
    DollSystem: typeof import('./src/components/Doll/DollSystem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    FormDetail: typeof import('./src/components/FormDetail.vue')['default']
    OctopusTakoyaki: typeof import('./src/components/OctopusTakoyaki.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectAppearance: typeof import('./src/components/Doll/SelectAppearance.vue')['default']
    SelectApproance: typeof import('./src/components/Doll/SelectApproance.vue')['default']
    SelectLanguageOption: typeof import('./src/components/SelectLanguageOption.vue')['default']
    SelectOption: typeof import('./src/components/selectOption.vue')['default']
    ShowDoll: typeof import('./src/components/Doll/ShowDoll.vue')['default']
  }
}
